const dareBtn = document.querySelector('#dare-btn');
const truthBtn = document.querySelector('#truth-btn');
const questionContainer = document.querySelector('#question-container');

const dares = [
    
  'Pretend you’re a cat and start licking yourself.',
  'Go up to a stranger and ask for a hug.',
  'Sing the alphabet without moving your mouth.',
  'Pretend to be a chicken for the next minute.',
  'Do the worm.',
  'Pretend to be a robot.',
  'Tell a joke that makes everyone groan.',
  'Pretend to be a celebrity for a day.',
  'Talk in a silly voice for the rest of the game.',
  'Wear your shirt on backwards for the next hour.',
  'Call a friend and pretend to be someone else.',
  'Tell a story backwards.',
  'Balance a spoon on your nose for 10 seconds.',
  'Pretend to be a penguin for the next minute.',
  'Do an impression of a famous person.',
  'Pretend to be a monkey.',
  'Wear your shoes on the wrong feet for the next hour.',
  'Tell a story using only emojis.',
  'Pretend to be a superhero.',
  'Do your best impression of a cartoon character.',
  'Wear a hat for the rest of the game.',
  'Pretend to be a frog.',
  'Balance a pencil on your upper lip for 10 seconds.',
  'Pretend to be a pirate.',
  'Wear a funny hat for the next hour.',
  'Tell a funny story from your childhood.',
  'Pretend to be a statue.',
  'Wear your socks on your hands for the next hour.',
  'Tell a story using only three words.',
  'Pretend to be a ghost.',
  'Do a handstand against the wall.',
  'Pretend to be a chef.',
  'Wear a necklace made of toilet paper for the rest of the game.',
  'Talk in a British accent for the next hour.',
  'Pretend to be a zombie.',
  'Do the chicken dance.',
  'Pretend to be a cowboy.',
  'Wear your pants backwards for the next hour.',
  'Tell a joke that makes everyone laugh.',
  'Pretend to be a dog and fetch an imaginary ball.',
  'Put your shirt on inside out for the next hour.',
  'Pretend to be a rock star.',
  'Do a cartwheel.',
  'Pretend to be a mime.',
  'Wear your watch on your other wrist for the next hour.',
  'Tell a story about a time you got lost.',
  'Pretend to be a ninja.',
  'Wear a bandana for the rest of the game.',
  'Pretend to be a bird.',
  'Do a dance from a popular music video.',
  'Pretend to be a spy.',
  'Wear your hair in a crazy style for the next hour.',
  'Tell a joke in a foreign accent.',
  'Pretend to be a dinosaur.',
  'Balance a spoon on your nose for 30 seconds.',
  'Pretend to be a superhero and save the day.',
  'Do the floss dance.',
  'Pretend to be a clown.',
  'Wear a sticker on your forehead for the rest of the game.',
  'Tell a story about your first crush.',
  'Pretend to be a robot and malfunction.',
  'Wear a pair of sunglasses for the next hour.',
  'Pretend to be a mermaid or merman.',
  'Balance a pencil on your head for 10 seconds.',
  'Tell a funny story about your pet.',
  'Pretend to be a dragon.',
  'Do a silly dance.',
  'Pretend to be a ghost and say "Boo!"',
  'Wear a cape for the rest of the game.',
  'Tell a story about a time you embarrassed yourself.',
];

const truths = [
    'What is the most embarrassing thing you have ever done in front of your friends?',
'What is the most embarrassing thing you have ever done in front of your coworkers?',
'What is the most embarrassing thing you have ever done in front of your boss?',
'What is the most embarrassing thing you have ever done in front of your crush?',
'What is the most embarrassing thing you have ever done on a date?',
'What is the most embarrassing thing you have ever done in front of your significant other?',
'What is the most embarrassing thing you have ever done in front of your family?',
'What is the most embarrassing thing you have ever done in front of a stranger?',
'What is the most embarrassing thing you have ever done while traveling?',
'What is the most embarrassing thing you have ever done in front of a celebrity?',
'What is the most embarrassing thing you have ever done in public?',
'What is the most embarrassing thing you have ever said to your ex?',
'What is the most embarrassing thing you have ever done while home alone?',
'What is the most embarrassing thing you have ever done at a job?',
'What is the most embarrassing thing you have ever done at a party?',
'What is the most embarrassing thing you have ever done on a video call?',
'What is the most embarrassing thing you have ever done on a first date?',
'What is the most embarrassing thing you have ever done in front of your teacher?',
'What is the most embarrassing thing you have ever done on social media?',
'What is the most embarrassing thing you have ever done while giving a speech?',
'What is the most embarrassing thing you have ever done in front of your neighbors?',
'What is the most embarrassing thing you have ever done at a concert?',
'What is the most embarrassing thing you have ever done in front of your kids?',
'What is the most embarrassing thing you have ever done while exercising?',
'What is the most embarrassing thing you have ever done while grocery shopping?',
'What is the most embarrassing thing you have ever done in a movie theater?',
'What is the most embarrassing thing you have ever done while cooking?',
'What is the most embarrassing thing you have ever done in a dressing room?',
'What is the most embarrassing thing you have ever done at a restaurant?',
'What is the most embarrassing thing you have ever done on a job interview?',
'What is the most embarrassing thing you have ever done while drunk?',
'What is the most embarrassing thing you have ever done in front of your partner’s family?',
'What is the most embarrassing thing you have ever done at a wedding?',
'What is the most embarrassing thing you have ever done in a gym?',
'What is the most embarrassing thing you have ever done in a public restroom?',
'What is the most embarrassing thing you have ever done while dancing?',
'What is the most embarrassing thing you have ever done while singing?',
'What is the most embarrassing thing you have ever done in front of a crush’s friends?',
'What is the most embarrassing thing you have ever done in front of a crush’s parents?',
'What is the most embarrassing thing you have ever done on a plane?',
'What is the most embarrassing thing you have ever done on a train?',
'What is the most embarrassing thing you have ever done on a bus?',
'What is the most embarrassing thing you have ever done on a boat?',
'What is the most embarrassing thing you have ever done in a meeting?',
'What is the most embarrassing thing you have ever done in a job training?',
'What is the most embarrassing thing you have ever done at a theme park?',
'What is the most embarrassing thing you have ever done in a haunted house?',
'What is the most embarrassing thing you have ever done in a museum?',
    'What is the most embarrassing thing you have ever done in front of your significant other’s family?',
'Have you ever had a crush on a friend’s significant other?',
'What is the most embarrassing thing you have ever done while trying to impress someone?',
'What is the most embarrassing thing you have ever done while trying to be cool?',
'Have you ever pretended to like something just to fit in?',
'What is the most embarrassing thing you have ever done while trying to be funny?',
'What is the most embarrassing thing you have ever done while trying to be romantic?',
'Have you ever had a crush on a celebrity?',
'What is the most embarrassing thing you have ever done in front of a celebrity?',
'What is the most embarrassing thing you have ever done in front of a teacher or professor?',
'Have you ever cheated on a school assignment?',
'What is the most embarrassing thing you have ever done while trying to be trendy?',
'What is the most embarrassing thing you have ever done while trying to be edgy?',
'What is the most embarrassing thing you have ever done while trying to be rebellious?',
'Have you ever lied to a therapist or counselor?',
'What is the most embarrassing thing you have ever done in front of a crush’s friend?',
'What is the most embarrassing thing you have ever done while on a video call?',
'Have you ever accidentally sent a text to the wrong person?',
'What is the most embarrassing thing you have ever done in a job interview?',
'What is the most embarrassing thing you have ever done while on a date with someone you met online?',
'What is the most embarrassing thing you have ever done while trying to be athletic?',
'What is the most embarrassing thing you have ever done while trying to be musical?',
'What is the most embarrassing thing you have ever done while trying to be artistic?',
'What is the most embarrassing thing you have ever done while trying to be intellectual?',
'What is the most embarrassing thing you have ever done while trying to be stylish?',
'What is the most embarrassing thing you have ever done while trying to be popular?',
'What is the most embarrassing thing you have ever done while trying to be sophisticated?',
'What is the most embarrassing thing you have ever done while trying to be cultured?',
'What is the most embarrassing thing you have ever done while trying to be spiritual?',
'What is the most embarrassing thing you have ever done while trying to be trendy on social media?',
'Have you ever lied to your partner about something important?',
'What is the most embarrassing thing you have ever done while trying to be healthy?',
'What is the most embarrassing thing you have ever done while trying to be environmentally friendly?',
'What is the most embarrassing thing you have ever done while trying to be charitable?',
'What is the most embarrassing thing you have ever done while trying to be politically correct?',
'What is the most embarrassing thing you have ever done while trying to be a good person?',
'What is the most embarrassing thing you have ever done while trying to be a role model?',
'What is the most embarrassing thing you have ever done while trying to be a leader?',
'What is the most embarrassing thing you have ever done while trying to be successful?',
'What is the most embarrassing thing you have ever done while trying to be rich?',
'What is the most embarrassing thing you have ever done while trying to be famous?',
'What is the most embarrassing thing you have ever done while trying to be powerful?',
'What is the most embarrassing thing you have ever done while trying to be popular on social media?',
'What is the most embarrassing thing you have ever done while trying to be funny on social media?',
    'What is your biggest secret?',
'Have you ever stolen something?',
'What is the most illegal thing you have ever done?',
'What is the most embarrassing thing you have ever done?',
'Have you ever lied to your best friend?',
'Have you ever lied to your significant other?',
'What is the most trouble you have ever been in with the law?',
'Have you ever cheated on someone?',
'What is the biggest lie you have ever told?',
'Have you ever done drugs?',
'What is your biggest regret?',
'Have you ever had a crush on someone who was in a relationship?',
'What is your biggest insecurity?',
'What is the worst thing you have ever done to a friend?',
'Have you ever cheated on a test?',
'What is the most embarrassing thing that has ever happened to you?',
'Have you ever lied to your parents?',
'What is something you have never told anyone?',
'What is your deepest, darkest fear?',
'What is the most embarrassing thing you have ever posted on social media?',
'Have you ever been in love with someone you couldn’t have?',
'Have you ever had a one night stand?',
'What is the most embarrassing thing you have ever said to someone?',
'What is the most inappropriate thing you have ever done?',
'What is the most embarrassing thing you have ever worn?',
'What is the worst thing you have ever said behind someone’s back?',
'Have you ever been attracted to someone of the same gender?',
'Have you ever lied to get out of trouble?',
'What is the most money you have ever stolen?',
'What is the most selfish thing you have ever done?',
'What is the most embarrassing nickname you have ever had?',
'Have you ever cheated on a significant other?',
'What is the worst date you have ever been on?',
'What is the most embarrassing thing that has ever happened to you in school?',
'What is the most embarrassing thing that has ever happened to you at work?',
'What is the most trouble you have ever gotten into with your boss?',
'What is the most embarrassing thing you have ever done at a party?',
'Have you ever lied to your doctor?',
'What is the most embarrassing thing you have ever done in front of a crush?',
'Have you ever stalked someone on social media?',
'What is the most embarrassing thing you have ever done in front of a crowd?',
'What is the most embarrassing thing you have ever done in a public place?',
'What is the most embarrassing thing you have ever done while on a date?',
'What is the most embarrassing thing you have ever said to your crush?',
'What is the most embarrassing thing you have ever done on stage?',
'What is the most embarrassing thing you have ever said to your boss?',
'What is the most embarrassing thing you have ever done in front of your parents?',
'What is the most embarrassing thing you have ever done while drunk?',
'What is the most embarrassing thing you have ever done on social media?',
'What is the most embarrassing thing you have ever done on a job interview?',
'Have you ever lied on your resume?',
'What is the most embarrassing thing you have ever said to a teacher?',
'What is the most embarrassing thing you have ever done at a family gathering?',
'What is the most embarrassing thing you have ever done on vacation?',
'What is the most embarrassing thing you have ever done on a school trip?',
'What is the most embarrassing thing you have ever done in front of your crush’s parents?',
'What is the most embarrassing thing you have ever said to a police officer?',
'What is the most embarrassing thing you have ever done in front of your friends?',
'What is the most embarrassing thing you have ever done in front of your coworkers?',
  'Have you ever cheated on a test?',
  'What is your biggest fear?',
  'What is the most embarrassing thing that has ever happened to you?',
  'Have you ever lied to your parents?',
  'What is the craziest thing you have ever done?',
  'What is your biggest regret?',
  'What is your dream job?',
  'Have you ever stolen anything?',
  'What is the worst date you have ever been on?',
  'What is the most trouble you have ever gotten into?',
];

function generateRandomIndex(array) {
  return Math.floor(Math.random() * array.length);
}

function generateDare() {
  const index = generateRandomIndex(dares);
  showQuestion(dares[index]);
}

function generateTruth() {
  const index = generateRandomIndex(truths);
  showQuestion(truths[index]);
}

function showQuestion(question) {
  const questionEl = document.createElement('p');
  questionEl.innerText = question;
  
  questionContainer.innerHTML = '';
  questionContainer.appendChild(questionEl);
}

dareBtn.addEventListener('click', generateDare);
truthBtn.addEventListener('click', generateTruth);
